//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.05 at 05:46:14 AM BRT 
//


package fortress.lighthouse.session.service.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for deviceId complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="deviceId">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="imei" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cdma" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="androidId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deviceId", propOrder = {
    "imei",
    "cdma",
    "androidId"
})
public class DeviceId {

    @XmlElement(required = true)
    protected String imei;
    @XmlElement(required = true)
    protected String cdma;
    @XmlElement(required = true)
    protected String androidId;

    /**
     * Gets the value of the imei property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImei() {
        return imei;
    }

    /**
     * Sets the value of the imei property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImei(String value) {
        this.imei = value;
    }

    /**
     * Gets the value of the cdma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdma() {
        return cdma;
    }

    /**
     * Sets the value of the cdma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdma(String value) {
        this.cdma = value;
    }

    /**
     * Gets the value of the androidId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAndroidId() {
        return androidId;
    }

    /**
     * Sets the value of the androidId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAndroidId(String value) {
        this.androidId = value;
    }

}
