//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.05 at 05:46:14 AM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://fortress/lighthouse/session/service/v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fortress.lighthouse.session.service.v1;
